<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-15T16:02:39 IST" name="Suite" finished-at="2024-08-15T16:02:42 IST" duration-ms="3451">
    <groups>
    </groups>
    <test started-at="2024-08-15T16:02:39 IST" name="Test" finished-at="2024-08-15T16:02:42 IST" duration-ms="3451">
      <class name="apiTest.GetRequestTest">
        <test-method signature="getAllUsers()[pri:0, instance:apiTest.GetRequestTest@341a8659]" started-at="2024-08-15T16:02:39 IST" name="getAllUsers" finished-at="2024-08-15T16:02:39 IST" duration-ms="115" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unexpected error occurred: HTTP method not supported.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unexpected error occurred: HTTP method not supported.
at org.testng.Assert.fail(Assert.java:111)
at apiTest.GetRequestTest.getAllUsers(GetRequestTest.java:51)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllUsers -->
        <test-method signature="getSingleUser()[pri:0, instance:apiTest.GetRequestTest@341a8659]" started-at="2024-08-15T16:02:39 IST" name="getSingleUser" finished-at="2024-08-15T16:02:42 IST" duration-ms="3230" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getSingleUser -->
      </class> <!-- apiTest.GetRequestTest -->
      <class name="apiTest.PostRequestTest">
        <test-method signature="LoginUserToken()[pri:0, instance:apiTest.PostRequestTest@2f19f2aa]" started-at="2024-08-15T16:02:42 IST" name="LoginUserToken" finished-at="2024-08-15T16:02:42 IST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginUserToken -->
      </class> <!-- apiTest.PostRequestTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
